# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter:  mysql2
  encoding: utf8
  database: ddj
  username: ddj
  password: ddj
  host:     192.168.33.14
  port:     3306
  pool:     5
  timeout:  5000

development:
  <<: *default

node1:
  <<: *default

node2:
  <<: *default

